name: Lint, Test, Deploy
on:
  issues:
    types: [opened, synchronize, reopened]

jobs:
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Deploy
        run: echo "${{ toJSON(github) }}"


